### PR TITLE
Add null check

### PR DESCRIPTION
**Pull request by Matthias1590**
Check if useragent is null before accessing fields

### CODE REVIEW

**Comment by jcompagner** [comment]
just wondering, when do you have a useragent string but that won't result in a parsed one?

**Comment by Matthias1590** [comment]
No clue how this would happen, just something I encountered in our logs somewhere. After checking the source of the ua_parser library used I don't see it returning null anywhere in any version

**Comment by Matthias1590** [comment]
```
2024-02-22 11:52	http-nio-8080-exec-939	ERROR	com.servoy.j2db.util.Debug	Cannot read field "family" because "userAgent" is null	 	 
java.lang.NullPointerException: Cannot read field "family" because "userAgent" is null
at com.servoy.j2db.server.headlessclient.util.HCUtils.supportsContentSecurityPolicyLevel3(HCUtils.java:208) ~[j2dbdev.jar:2022.9.1.3804]
at com.servoy.j2db.server.ngclient.AngularIndexPageWriter.getContentSecurityPolicyConfig(AngularIndexPageWriter.java:383) ~[servoy_ngclient_2022.9.1.3804.jar:?]
at com.servoy.j2db.server.ngclient.AngularIndexPageWriter.addcontentSecurityPolicyHeader(AngularIndexPageWriter.java:350) ~[servoy_ngclient_2022.9.1.3804.jar:?]
at com.servoy.j2db.server.ngclient.NGClientEntryFilter.doFilter(NGClientEntryFilter.java:361) [servoy_ngclient_2022.9.1.3804.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.84]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.84]
at org.sablo.filter.SecurityFilter.doFilter(SecurityFilter.java:48) [sablo_2022.9.1.3804.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.84]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.84]
at org.sablo.filter.SeparateSessionFilter.doFilter(SeparateSessionFilter.java:80) [sablo_2022.9.1.3804.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.84]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.84]
at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web.jar:2.17.1]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.84]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.84]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [catalina.jar:9.0.84]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.84]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [catalina.jar:9.0.84]
at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:289) [catalina.jar:9.0.84]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.84]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.84]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670) [catalina.jar:9.0.84]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.84]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:9.0.84]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.84]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.84]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat-coyote.jar:9.0.84]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) [tomcat-coyote.jar:9.0.84]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.84]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.84]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.84]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.84]
at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by jcompagner** [comment]
ah can you then alter this pull request a bit, and adding a log statement for this scenario (so in that if)?
because it could be that we have to update something else to support this specific user agent.

**Comment by Matthias1590** [comment]
Oh, my bad, this seems to be caused by the fact the userAgent string isn't null checked in previous versions. Didn't see commit [7c1990d44886b6860e6a77033e7a2fbfe83cbff6](https://github.com/Servoy/servoy-client/commit/7c1990d44886b6860e6a77033e7a2fbfe83cbff6)

**Comment by jcompagner** [comment]
that null check should be in 2023.12 and higher, not sure what you are using?

**Comment by Matthias1590** [comment]
2022.09.1 I believe

**Pull request closed without merging**
